[package]
name = "chess"
version = "0.1.0"
authors = ["Michael Hoy <mjh@mjhoy.com>"]
autobins = false
edition = "2018"

[lib]
name = "chess"
path = "src/lib.rs"

[[bin]]
name = "chess"
path = "src/bin/main.rs"

[dependencies]
itertools = "0.7.8"
nom = "4.2.2"
